# Generated by Django 4.2.16 on 2024-09-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('expected_people', models.IntegerField()),
                ('guest_names', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('estimated_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.TimeField()),
                ('poster', models.ImageField(upload_to='posters/')),
            ],
            options={
                'permissions': [('can_view_event', 'Can view event'), ('can_edit_event', 'Can edit event'), ('can_manage_event', 'Can manage event')],
            },
        ),
    ]
